
services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deployment_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: deployment_backend
    restart: always
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./backend/static_sites:/app/static_sites
    ports:
      - "8000:8000"
      - "11000-11100:11000-11100"


  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: deployment_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      NEXT_PUBLIC_FRONTEND_URL: http://localhost:3000



volumes:
  postgres_data:

