version: '3.9'

services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deployment_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: deployment_backend
    restart: always
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./backend/static_sites:/app/static_sites
    ports:
      - "8000:8000"
      - "${WEBSITE_MIN_PORT}-${WEBSITE_MAX_PORT}:${WEBSITE_MIN_PORT}-${WEBSITE_MAX_PORT}"
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db:5432/deployment_db
      SECRET_KEY: your-secret-key-here
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 604800
      STATIC_SITES_DIR: /app/static_sites
      WEBSITE_MIN_PORT: 11000
      WEBSITE_MAX_PORT: 11100

volumes:
  postgres_data:

